Repository apigee/apigee-edge-drupal, pull requests merged in 2019-05, with the labels that each got.

#183 DRUP-723 Change “My Apps” to just “Apps”
  README.md
  apigee_edge.links.menu.yml
  apigee_edge.routing.yml
  modules/apigee_edge_teams/src/Routing/TeamAppByNameRouteAlterSubscriber.php
  src/Access/AppsPageAccessCheck.php
  src/Entity/DeveloperAppRouteProvider.php
  src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php
  src/EventSubscriber/DeveloperStatusWarningSubscriber.php
  src/Plugin/Menu/MyAppsMenuLink.php
  tests/src/Functional/CacheTest.php
  tests/src/Functional/DeveloperAppUITest.php
Labels: apigee_edge, bc breaking

#181 DRUP-687 Added default Apigee entity theme
  apigee_edge.module
  css/apigee_edge.app_listing.css
  css/apigee_edge.app_view.css
  src/Annotation/EdgeEntityType.php
  src/Entity/AppViewBuilder.php
  src/Entity/EdgeEntityType.php
  src/Entity/EdgeEntityViewBuilder.php
  templates/apigee-entity--app.html.twig
  templates/apigee-entity.html.twig
Labels: apigee_edge, enhancement

#192 DRUP-639 Fix failing Authentication form test after 19.03.01
  src/KeyEntityFormEnhancer.php
  tests/src/FunctionalJavascript/Form/AuthenticationFormJsTest.php
Labels: apigee_edge, bug

#188 DRUP-639 Drupal 8.7 support
  .travis.yml
  composer.json
  src/Entity/Controller/Cache/DeveloperAppCacheFactory.php
  src/Entity/Controller/Cache/DeveloperAppNameCacheFactory.php
  src/Entity/Storage/DeveloperAppStorage.php
  src/Entity/Storage/FieldableEdgeEntityStorageBase.php
  tests/src/Functional/DeveloperAppFieldTest.php
Labels: apigee_edge, bc breaking

#184 DRUP-684 Sanitize MINT organizations in URI
  modules/apigee_edge_debug/src/Plugin/DebugMessageFormatter/DebugMessageFormatterPluginBase.php
Labels: apigee_edge_debug, bug

#195 [DRUP-787] Lock drupal core version to ~8.7.0
  composer.json
Labels: cla: yes

#190 DRUP-761 Move API product access tab
  apigee_edge.links.task.yml
Labels: apigee_edge

#196 [DRUP-738] Rename the default RBAC attribute value from `APIGEE_EDGE_…
  modules/apigee_edge_apiproduct_rbac/config/install/apigee_edge_apiproduct_rbac.settings.yml
Labels: cla: yes

#197 [DRUP-724] Update requirements, installation and patches section in README
  README.md
Labels: cla: yes

#198 [DRUP-803] Deprecate apidocs module
  modules/apigee_edge_apidocs/README.md
  modules/apigee_edge_apidocs/apigee_edge_apidocs.info.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.install
  modules/apigee_edge_teams/src/EventSubscriber/TeamStatusWarningSubscriber.php
  modules/apigee_edge_teams/src/TeamPermissionHandler.php
  src/EventSubscriber/DeveloperStatusWarningSubscriber.php
  src/KeyEntityFormEnhancer.php
Labels: cla: yes

#199 [DRUP-747] Comment fixes
  apigee_edge.module
  modules/apigee_edge_apiproduct_rbac/apigee_edge_apiproduct_rbac.module
  src/ParamConverter/ApigeeEdgeLoadUnchangedEntity.php
  tests/src/Functional/ApiProductAccessTest.php
Labels: cla: yes

#201 [DRUP-803] Add missing set statement in the team permission handler.
  modules/apigee_edge_teams/src/TeamPermissionHandler.php
Labels: cla: yes

#200 DRUP-789 Fix PHP notice caused by missing array key
  src/KeyEntityFormEnhancer.php
Labels: cla: no

#207 Bump minimum Drupal core requirement
  apigee_edge.info.yml
Labels: cla: yes

#208 Change disclaimer
  README.md
Labels: cla: yes

#202 [DRUP-803] Removes the API Docs submodule from the `apigee_edge` module.
  modules/apigee_edge_apidocs/README.md
  modules/apigee_edge_apidocs/apigee_edge_apidocs.info.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.install
  modules/apigee_edge_apidocs/apigee_edge_apidocs.links.action.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.links.menu.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.links.task.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.module
  modules/apigee_edge_apidocs/apigee_edge_apidocs.permissions.yml
  modules/apigee_edge_apidocs/apigee_edge_apidocs.services.yml
  modules/apigee_edge_apidocs/config/optional/views.view.apigee_edge_api_docs.yml
  modules/apigee_edge_apidocs/src/ApiDocAccessControlHandler.php
  modules/apigee_edge_apidocs/src/ApiDocHtmlRouteProvider.php
  modules/apigee_edge_apidocs/src/ApiDocListBuilder.php
  modules/apigee_edge_apidocs/src/Controller/ApiDocController.php
  modules/apigee_edge_apidocs/src/Entity/ApiDoc.php
  modules/apigee_edge_apidocs/src/Entity/ApiDocInterface.php
  modules/apigee_edge_apidocs/src/Form/ApiDocDeleteForm.php
  modules/apigee_edge_apidocs/src/Form/ApiDocForm.php
  modules/apigee_edge_apidocs/src/Form/ApiDocSettingsForm.php
  modules/apigee_edge_apidocs/tests/src/Functional/ApiDocsAccessTest.php
  modules/apigee_edge_apidocs/tests/src/Functional/ApiDocsAdminTest.php
  modules/apigee_edge_apidocs/tests/src/Kernel/ApidocEntityTest.php
Labels: cla: yes

#209 Readme Update
  README.md
Labels: cla: yes
