Repository apigee/apigee-edge-drupal, pull requests merged in 2023-09, with the labels that each got.

#918 Extract user deletion into a new service
  apigee_edge.module
  apigee_edge.services.yml
  modules/apigee_edge_teams/apigee_edge_teams.module
  modules/apigee_edge_teams/apigee_edge_teams.services.yml
  modules/apigee_edge_teams/src/User/RemoveTeamRolesOfUserSynchronousPostUserDeleteActionPerformer.php
  src/User/PostUserDeleteActionPerformerInterface.php
  src/User/RemoveRelatedDeveloperAccountSynchronousPostUserDeleteActionPerformer.php
Labels: enhancement

#907 Added php 8.2 in github action
  .github/workflows/php.yml
Labels: PHP 8.2

#929 Fix isOrganizationApigeeX() on null issue
  modules/apigee_edge_teams/src/Entity/Form/TeamForm.php
Labels: bug

#926 Added changes for AppGroup Apps pagination
  modules/apigee_edge_teams/src/Entity/Controller/TeamAppController.php
  src/Entity/Controller/AppByOwnerController.php
Labels: enhancement

#934 Added changes for AppGroup Apps pagination-3x
  modules/apigee_edge_teams/src/Entity/Controller/TeamAppController.php
  src/Entity/Controller/AppByOwnerController.php
Labels: enhancement

#908 Added support for PHP 8.2
  composer.json
  src/Form/AppAnalyticsFormBase.php
Labels: PHP 8.2

#937 Bump Client PHP requirement version
  composer.json
Labels: enhancement

#942 Fix dev version string in user agent info
  src/SDKConnector.php
Labels: bug
