Repository apigee/apigee-edge-drupal, pull requests merged in 2024-01, with the labels that each got.

#1006 Fix for $app_warnings_checker is deprecation message
  modules/apigee_edge_teams/src/Entity/ListBuilder/TeamAppListByTeam.php
  src/Entity/ListBuilder/AppListBuilder.php
  src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php
Labels: deprecation

#1025 Fix test case failing due to getCacheTags() on null error
  tests/modules/apigee_mock_api_client/tests/src/Traits/ApigeeMockApiClientHelperTrait.php
Labels: bug

#1014 Renaming title and descriptions in module info file from Apigee Edge to Apigee
  apigee_edge.info.yml
  composer.json
  tests/src/Kernel/UserAgentTest.php
Labels: enhancement

#1015 Rename Apigee Edge to Apigee in README.md file
  README.md
Labels: enhancement

#1018 Rename Apigee Edge to Apigee in install, menu and routing yml files
  apigee_edge.install
  apigee_edge.links.menu.yml
  apigee_edge.routing.yml
  tests/src/Functional/StatusReportTest.php
Labels: enhancement
